import { v4 as uuidv4 } from "uuid";

const InitialTodos = [
  {
    id: uuidv4(),
    name: "Learn Handstand",
    description: "Practice handstands for 10 minutes every day",
    software: [],
    days: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
    goalType: "short-term",
    dueDate: "2023-06-30",
    isActive: true,
    checked: false,
    finished: false,
    tags: ['Fitness', 'Hobbies'],
  },
  {
    id: uuidv4(),
    name: "Write Essay",
    description: "Complete a 2000-word essay on AI",
    software: ["microsoft_word"],
    days: ["Monday", "Wednesday", "Friday"],
    goalType: "short-term",
    dueDate: "2023-06-15",
    isActive: true,
    checked: false,
    finished: false,
    tags: ['School', 'Learning'],
  },
  {
    id: uuidv4(),
    name: "Learn React",
    description: "Study React documentation and complete a tutorial",
    software: ["visual_studio_code"],
    days: ["Tuesday", "Thursday"],
    goalType: "long-term",
    dueDate: "2023-08-01",
    isActive: true,
    checked: false,
    finished: false,
    tags: ['Career', 'Learning'],
  },
  {
    id: uuidv4(),
    name: "Buy Groceries",
    description: "Purchase groceries for the week",
    software: [],
    days: ["Saturday"],
    goalType: "short-term",
    dueDate: "2023-05-07",
    isActive: true,
    checked: false,
    finished: false,
    tags: ['Home', 'Health'],
  },
  {
    id: uuidv4(),
    name: "Learn Guitar",
    description: "Practice guitar for 30 minutes every day",
    software: [],
    days: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
    goalType: "long-term",
    dueDate: "2023-12-31",
    isActive: true,
    checked: false,
    finished: false,
    tags: ['Hobbies', 'Creativity'],
  },
];

export default InitialTodos;
